apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sloth
spec:
  selector:
    app: sloth
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
